/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppMyLearningRouteImport } from './routes/_app.my-learning'
import { Route as AppSessionsRouteImport } from './routes/_app.sessions'
import { Route as AppCoursesIndexRouteImport } from './routes/_app.courses.index'
import { Route as AppCoursesIdRouteImport } from './routes/_app.courses.$id'
import { Route as AppManagerIndexRouteImport } from './routes/_app.manager.index'
import { Route as AppManagerAssignRouteImport } from './routes/_app.manager.assign'
import { Route as AppManagerEmployeesRouteImport } from './routes/_app.manager.employees'
import { Route as AppManagerReportRouteImport } from './routes/_app.manager.report'
import { Route as AppManagerReportsRouteImport } from './routes/_app.manager.reports'
import { Route as AppPathsIndexRouteImport } from './routes/_app.paths.index'
import { Route as AppPathsIdRouteImport } from './routes/_app.paths.$id'
import { Route as AppManagerCooursesNewRouteImport } from './routes/_app.manager.coourses.new'
import { Route as AppManagerCoursesNewRouteImport } from './routes/_app.manager.courses.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppMyLearningRoute = AppMyLearningRouteImport.update({
  id: '/my-learning',
  path: '/my-learning',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsRoute = AppSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesIndexRoute = AppCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesIdRoute = AppCoursesIdRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppManagerIndexRoute = AppManagerIndexRouteImport.update({
  id: '/manager/',
  path: '/manager/',
  getParentRoute: () => AppRoute,
} as any)
const AppManagerAssignRoute = AppManagerAssignRouteImport.update({
  id: '/manager/assign',
  path: '/manager/assign',
  getParentRoute: () => AppRoute,
} as any)
const AppManagerEmployeesRoute = AppManagerEmployeesRouteImport.update({
  id: '/manager/employees',
  path: '/manager/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppManagerReportRoute = AppManagerReportRouteImport.update({
  id: '/manager/report',
  path: '/manager/report',
  getParentRoute: () => AppRoute,
} as any)
const AppManagerReportsRoute = AppManagerReportsRouteImport.update({
  id: '/manager/reports',
  path: '/manager/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPathsIndexRoute = AppPathsIndexRouteImport.update({
  id: '/paths/',
  path: '/paths/',
  getParentRoute: () => AppRoute,
} as any)
const AppPathsIdRoute = AppPathsIdRouteImport.update({
  id: '/paths/$id',
  path: '/paths/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppManagerCooursesNewRoute = AppManagerCooursesNewRouteImport.update({
  id: '/manager/coourses/new',
  path: '/manager/coourses/new',
  getParentRoute: () => AppRoute,
} as any)
const AppManagerCoursesNewRoute = AppManagerCoursesNewRouteImport.update({
  id: '/manager/courses/new',
  path: '/manager/courses/new',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/my-learning': typeof AppMyLearningRoute
  '/sessions': typeof AppSessionsRoute
  '/courses/$id': typeof AppCoursesIdRoute
  '/manager/assign': typeof AppManagerAssignRoute
  '/manager/employees': typeof AppManagerEmployeesRoute
  '/manager/report': typeof AppManagerReportRoute
  '/manager/reports': typeof AppManagerReportsRoute
  '/paths/$id': typeof AppPathsIdRoute
  '/courses/': typeof AppCoursesIndexRoute
  '/manager/': typeof AppManagerIndexRoute
  '/paths/': typeof AppPathsIndexRoute
  '/manager/coourses/new': typeof AppManagerCooursesNewRoute
  '/manager/courses/new': typeof AppManagerCoursesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/my-learning': typeof AppMyLearningRoute
  '/sessions': typeof AppSessionsRoute
  '/courses/$id': typeof AppCoursesIdRoute
  '/manager/assign': typeof AppManagerAssignRoute
  '/manager/employees': typeof AppManagerEmployeesRoute
  '/manager/report': typeof AppManagerReportRoute
  '/manager/reports': typeof AppManagerReportsRoute
  '/paths/$id': typeof AppPathsIdRoute
  '/courses': typeof AppCoursesIndexRoute
  '/manager': typeof AppManagerIndexRoute
  '/paths': typeof AppPathsIndexRoute
  '/manager/coourses/new': typeof AppManagerCooursesNewRoute
  '/manager/courses/new': typeof AppManagerCoursesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/my-learning': typeof AppMyLearningRoute
  '/_app/sessions': typeof AppSessionsRoute
  '/_app/courses/$id': typeof AppCoursesIdRoute
  '/_app/manager/assign': typeof AppManagerAssignRoute
  '/_app/manager/employees': typeof AppManagerEmployeesRoute
  '/_app/manager/report': typeof AppManagerReportRoute
  '/_app/manager/reports': typeof AppManagerReportsRoute
  '/_app/paths/$id': typeof AppPathsIdRoute
  '/_app/courses/': typeof AppCoursesIndexRoute
  '/_app/manager/': typeof AppManagerIndexRoute
  '/_app/paths/': typeof AppPathsIndexRoute
  '/_app/manager/coourses/new': typeof AppManagerCooursesNewRoute
  '/_app/manager/courses/new': typeof AppManagerCoursesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/my-learning'
    | '/sessions'
    | '/courses/$id'
    | '/manager/assign'
    | '/manager/employees'
    | '/manager/report'
    | '/manager/reports'
    | '/paths/$id'
    | '/courses/'
    | '/manager/'
    | '/paths/'
    | '/manager/coourses/new'
    | '/manager/courses/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/my-learning'
    | '/sessions'
    | '/courses/$id'
    | '/manager/assign'
    | '/manager/employees'
    | '/manager/report'
    | '/manager/reports'
    | '/paths/$id'
    | '/courses'
    | '/manager'
    | '/paths'
    | '/manager/coourses/new'
    | '/manager/courses/new'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/my-learning'
    | '/_app/sessions'
    | '/_app/courses/$id'
    | '/_app/manager/assign'
    | '/_app/manager/employees'
    | '/_app/manager/report'
    | '/_app/manager/reports'
    | '/_app/paths/$id'
    | '/_app/courses/'
    | '/_app/manager/'
    | '/_app/paths/'
    | '/_app/manager/coourses/new'
    | '/_app/manager/courses/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-learning': {
      id: '/_app/my-learning'
      path: '/my-learning'
      fullPath: '/my-learning'
      preLoaderRoute: typeof AppMyLearningRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions': {
      id: '/_app/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AppSessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses/': {
      id: '/_app/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof AppCoursesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses/$id': {
      id: '/_app/courses/$id'
      path: '/courses/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof AppCoursesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manager/': {
      id: '/_app/manager/'
      path: '/manager'
      fullPath: '/manager/'
      preLoaderRoute: typeof AppManagerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manager/assign': {
      id: '/_app/manager/assign'
      path: '/manager/assign'
      fullPath: '/manager/assign'
      preLoaderRoute: typeof AppManagerAssignRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manager/employees': {
      id: '/_app/manager/employees'
      path: '/manager/employees'
      fullPath: '/manager/employees'
      preLoaderRoute: typeof AppManagerEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manager/report': {
      id: '/_app/manager/report'
      path: '/manager/report'
      fullPath: '/manager/report'
      preLoaderRoute: typeof AppManagerReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manager/reports': {
      id: '/_app/manager/reports'
      path: '/manager/reports'
      fullPath: '/manager/reports'
      preLoaderRoute: typeof AppManagerReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/paths/': {
      id: '/_app/paths/'
      path: '/paths'
      fullPath: '/paths/'
      preLoaderRoute: typeof AppPathsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/paths/$id': {
      id: '/_app/paths/$id'
      path: '/paths/$id'
      fullPath: '/paths/$id'
      preLoaderRoute: typeof AppPathsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manager/coourses/new': {
      id: '/_app/manager/coourses/new'
      path: '/manager/coourses/new'
      fullPath: '/manager/coourses/new'
      preLoaderRoute: typeof AppManagerCooursesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manager/courses/new': {
      id: '/_app/manager/courses/new'
      path: '/manager/courses/new'
      fullPath: '/manager/courses/new'
      preLoaderRoute: typeof AppManagerCoursesNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppMyLearningRoute: typeof AppMyLearningRoute
  AppSessionsRoute: typeof AppSessionsRoute
  AppCoursesIdRoute: typeof AppCoursesIdRoute
  AppManagerAssignRoute: typeof AppManagerAssignRoute
  AppManagerEmployeesRoute: typeof AppManagerEmployeesRoute
  AppManagerReportRoute: typeof AppManagerReportRoute
  AppManagerReportsRoute: typeof AppManagerReportsRoute
  AppPathsIdRoute: typeof AppPathsIdRoute
  AppCoursesIndexRoute: typeof AppCoursesIndexRoute
  AppManagerIndexRoute: typeof AppManagerIndexRoute
  AppPathsIndexRoute: typeof AppPathsIndexRoute
  AppManagerCooursesNewRoute: typeof AppManagerCooursesNewRoute
  AppManagerCoursesNewRoute: typeof AppManagerCoursesNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppMyLearningRoute: AppMyLearningRoute,
  AppSessionsRoute: AppSessionsRoute,
  AppCoursesIdRoute: AppCoursesIdRoute,
  AppManagerAssignRoute: AppManagerAssignRoute,
  AppManagerEmployeesRoute: AppManagerEmployeesRoute,
  AppManagerReportRoute: AppManagerReportRoute,
  AppManagerReportsRoute: AppManagerReportsRoute,
  AppPathsIdRoute: AppPathsIdRoute,
  AppCoursesIndexRoute: AppCoursesIndexRoute,
  AppManagerIndexRoute: AppManagerIndexRoute,
  AppPathsIndexRoute: AppPathsIndexRoute,
  AppManagerCooursesNewRoute: AppManagerCooursesNewRoute,
  AppManagerCoursesNewRoute: AppManagerCoursesNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
